org.gradle.jvmargs = -Xmx3G
org.gradle.java.home = D:/.cleanroom/java/zulu25.36.15-ca-fx-jdk25.0.4-win_x64/zulu25.36.15-ca-fx-jdk25.0.4-win_x64

generate_sources_jar = true
generate_javadocs_jar = false

enable_junit_testing = true
show_testing_output = false

enable_shadow = false
enable_lwjglx = true

mod_version = 1.0.0
root_package = net.vas.rdpcore
mod_id = rdpcore
mod_name = RDP Core
mod_description = A world-level simulation framework that unifies modpack systems into a coherent cosmological-horror phenomenon

mod_url = 
mod_update_json = 
mod_authors = W9setlay
mod_credits = Inspired by cosmological horror and SCP Foundation concepts
mod_logo_path = 
mod_issue_tracker = 

minecraft_username = Developer
extra_jvm_args = 
enable_foundation_debug = false

publish_to_maven = false
publish_to_local_maven = false

maven_name = ${mod_name}
maven_url = 

use_access_transformer = false

is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name = 

use_asset_mover = false
