package net.vas.rdpcore.entity;

public enum RealityAnchorCapability {
    REALITY_STABILIZATION,
    TERRAIN_MUTATION_SUPPRESSION,
    BIOME_MUTATION_SUPPRESSION,
    ANOMALY_SUPPRESSION,
    DIMENSIONAL_LEAKAGE_SUPPRESSION,
    EVENT_SUPPRESSION
}
